### ISSUE TITLE
Not available on fabric multi-server.

### ISSUE THREAD

**Issue by 321098123** [doublemoon1119/MahjongCraft#13]
Installing mahjong table only forces the server to shut down.

log:
`[14:38:58] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: remainingTiles
        at doublemoon.mahjongcraft.blockentity.MahjongTableBlockEntity.<init>(MahjongTableBlockEntity.kt:53) ~[mahjongcraft-mc1.19.4-0.3.11.jar:?]
        at doublemoon.mahjongcraft.block.MahjongTable.method_10123(MahjongTable.kt:136) ~[mahjongcraft-mc1.19.4-0.3.11.jar:?]
        at net.minecraft.class_2818.method_12010(class_2818.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_30092(class_1937.java:230) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8652(class_1937.java:215) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7708(class_1747.java:163) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7712(class_1747.java:80) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7884(class_1747.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.method_7981(class_1799.java:274) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:359) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:786) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:762) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:679) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:38:58] [Server thread/ERROR]: This crash report has been saved to: /home/server/./crah-reports/crash-2024-05-24_14.38.58-server.txt
[14:38:58] [Server thread/INFO]: 0 games cleared
[14:38:58] [Server thread/INFO]: Stopping server
[14:38:58] [Server thread/INFO]: Saving players
[14:38:58] [Server thread/INFO]: 0000 lost connection: Server closed
[14:38:58] [Server thread/INFO]: 0000 left the game
[14:38:58] [Server thread/INFO]: Saving worlds
[14:38:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[14:39:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[14:39:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[14:39:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[14:39:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:39:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:39:02] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved `

**Comment by 24802** [comment]
compiled it and it works fine thank you

**Comment by 321098123** [comment]
compiled it and it works fine thank you
