### ISSUE TITLE
crash when game open

### ISSUE THREAD

**Issue by ipiiia** [doublemoon1119/MahjongCraft#4]
Description: Initializing game

java.lang.NoClassDefFoundError: io/github/cottonmc/cotton/gui/widget/WPlainPanel
	at doublemoon.mahjongcraft.client.gui.MahjongCraftHud.<init>(MahjongCraftHud.kt:27)
	at doublemoon.mahjongcraft.MahjongCraftClient.onInitializeClient$lambda-1(MahjongCraftClient.kt:110)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:103)
	at net.minecraft.class_437.handler$cke000$afterInitScreen(class_437.java:3327)
	at net.minecraft.class_437.method_25423(class_437.java:393)
	at net.minecraft.class_310.method_1507(class_310.java:993)
	at net.minecraft.class_310.<init>(class_310.java:637)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.cotton.gui.widget.WPlainPanel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at doublemoon.mahjongcraft.client.gui.MahjongCraftHud.<init>(MahjongCraftHud.kt:27)
	at doublemoon.mahjongcraft.MahjongCraftClient.onInitializeClient$lambda-1(MahjongCraftClient.kt:110)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:103)
	at net.minecraft.class_437.handler$cke000$afterInitScreen(class_437.java:3327)
	at net.minecraft.class_437.method_25423(class_437.java:393)
	at net.minecraft.class_310.method_1507(class_310.java:993)
	at net.minecraft.class_310.<init>(class_310.java:637)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by doublemoon1119** [comment]
These don't look like problems with my mod,
Can you give the complete log file.

**Comment by ipiiia** [comment]
> These don't look like problems with my mod,
> Can you give the complete log file.

hmm,, I don't know why but it's solved now
